# Generated by Django 3.0.6 on 2020-07-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuartoHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quarto_hotel', models.BigIntegerField()),
                ('nome_hotel', models.CharField(default='', max_length=200)),
                ('nome_quarto', models.CharField(default='', max_length=200)),
                ('descricao_quarto', models.TextField(max_length=500)),
                ('endereco', models.CharField(default='', max_length=350)),
                ('cidade', models.CharField(default='', max_length=350)),
                ('estado', models.CharField(default='', max_length=350)),
                ('pais', models.CharField(default='', max_length=350)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_hospedes', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passageiros', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=200)),
                ('senha', models.CharField(default='', max_length=50)),
                ('cpf', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_voo', models.BigIntegerField()),
                ('nome_companhia', models.CharField(default='', max_length=200)),
                ('classe', models.CharField(default='', max_length=200)),
                ('data_voo', models.DateTimeField()),
                ('aeroporto_origem', models.CharField(default='', max_length=5)),
                ('aeroporto_destino', models.CharField(default='', max_length=5)),
                ('pais_origem', models.CharField(default='', max_length=100)),
                ('pais_destino', models.CharField(default='', max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_passageiros', models.IntegerField(default=200)),
                ('cheio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVooPassageiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ultimo_sobrenome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=11)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.TipoDocumento')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.ReservaVoo')),
            ],
        ),
        migrations.AddField(
            model_name='reservavoo',
            name='voo',
            field=models.ManyToManyField(to='aplicacao.Voo'),
        ),
        migrations.CreateModel(
            name='ReservaQuartoHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('hospede_principal', models.BooleanField()),
                ('nome_hospede_principal', models.CharField(default='', max_length=250)),
                ('cafe_da_manha', models.BooleanField()),
                ('viagem_trabalho', models.BooleanField()),
                ('qtd_hospedes', models.IntegerField()),
                ('quarto_hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.QuartoHotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contato', models.CharField(default='', max_length=11)),
                ('seguro_viagem', models.BooleanField()),
                ('pgto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Pagamento')),
                ('reserva_hotel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.ReservaQuartoHotel')),
                ('reserva_voo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.ReservaVoo')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.StatusReserva')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Usuario')),
            ],
        ),
    ]
