# Generated by Django 3.0.6 on 2020-07-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
