# Generated by Django 3.0.6 on 2020-07-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pgto', models.BigIntegerField()),
                ('status', models.CharField(default='SEM_INFORMACAO', max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuartoHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quarto_hotel', models.BigIntegerField()),
                ('nome_hotel', models.CharField(default='SEM_INFORMACAO', max_length=200)),
                ('nome_quarto', models.CharField(default='SEM_INFORMACAO', max_length=200)),
                ('descrica_quarto', models.CharField(default='SEM_INFORMACAO', max_length=50)),
                ('max_hospedes', models.CharField(default='SEM_INFORMACAO', max_length=11)),
                ('disponivel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_voo', models.BigIntegerField()),
                ('nome_companhia', models.CharField(default='SEM_INFORMACAO', max_length=200)),
                ('classe', models.CharField(default='SEM_INFORMACAO', max_length=200)),
                ('data_voo', models.CharField(default='SEM_INFORMACAO', max_length=50)),
                ('origem', models.CharField(default='SEM_INFORMACAO', max_length=11)),
                ('destino', models.CharField(default='SEM_INFORMACAO', max_length=11)),
                ('max_passageiros', models.IntegerField()),
                ('cheio', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='SEM_INFORMACAO', max_length=11),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='SEM_INFORMACAO', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='SEM_INFORMACAO', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='SEM_INFORMACAO', max_length=200),
        ),
        migrations.CreateModel(
            name='ReservaVoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva_voo', models.BigIntegerField()),
                ('telefone_contato', models.CharField(default='SEM_INFORMACAO', max_length=11)),
                ('pgto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Pagamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Usuario')),
                ('voo', models.ManyToManyField(to='aplicacao.Voo')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaQuartoHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva_hotel', models.BigIntegerField()),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('hospede_principal', models.BooleanField()),
                ('nome_hospede_principal', models.CharField(default='SEM_INFORMACAO', max_length=100)),
                ('cafe_da_manha', models.BooleanField()),
                ('viagem_trabalho', models.BooleanField()),
                ('qtd_hospedes', models.IntegerField()),
                ('telefone_contato', models.CharField(default='SEM_INFORMACAO', max_length=11)),
                ('pgto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Pagamento')),
                ('quarto_hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.QuartoHotel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Usuario')),
            ],
        ),
    ]
