# Generated by Django 3.0.6 on 2020-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_auto_20200701_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quartohotel',
            name='descrica_quarto',
        ),
        migrations.AddField(
            model_name='quartohotel',
            name='descricap_quarto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quartohotel',
            name='max_hospedes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quartohotel',
            name='nome_hotel',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quartohotel',
            name='nome_quarto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservaquartohotel',
            name='nome_hospede_principal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservaquartohotel',
            name='telefone_contato',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='reservavoo',
            name='telefone_contato',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='voo',
            name='classe',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='voo',
            name='data_voo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='voo',
            name='destino',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='voo',
            name='nome_companhia',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='voo',
            name='origem',
            field=models.CharField(default='', max_length=11),
        ),
    ]
