# Generated by Django 3.0.6 on 2020-07-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_auto_20200704_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservavoo',
            name='passageiros',
            field=models.IntegerField(default=1),
        ),
    ]
