# Generated by Django 3.0.6 on 2020-07-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_delete_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.StatusReserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.Usuario'),
        ),
    ]
