# Generated by Django 3.0.6 on 2020-07-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_auto_20200701_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='id_pgto',
        ),
        migrations.RemoveField(
            model_name='quartohotel',
            name='id_quarto_hotel',
        ),
        migrations.RemoveField(
            model_name='reservaquartohotel',
            name='id_reserva_hotel',
        ),
        migrations.RemoveField(
            model_name='reservavoo',
            name='id_reserva_voo',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='id_voo',
        ),
    ]
