# Generated by Django 3.0.6 on 2020-07-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_auto_20200705_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaquartohotel',
            name='hospede_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservaquartohotel',
            name='quarto_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.QuartoHotel'),
        ),
    ]
