# Generated by Django 3.0.6 on 2020-07-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_auto_20200702_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quartohotel',
            old_name='descricap_quarto',
            new_name='descricao_quarto',
        ),
    ]
