# Generated by Django 3.0.6 on 2020-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_auto_20200702_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartohotel',
            name='descricao_quarto',
            field=models.TextField(max_length=500),
        ),
    ]
