# Generated by Django 3.0.6 on 2020-07-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_auto_20200705_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
