# Generated by Django 3.0.6 on 2020-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_reserva_data_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='seguro_viagem',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservaquartohotel',
            name='cafe_da_manha',
        ),
        migrations.RemoveField(
            model_name='reservaquartohotel',
            name='viagem_trabalho',
        ),
        migrations.AlterField(
            model_name='voo',
            name='aeroporto_destino',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='voo',
            name='aeroporto_origem',
            field=models.CharField(default='', max_length=500),
        ),
    ]
